spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kunmarket
    username: kmkunk
    password: kmkunk
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10 # 기본 페이지 사이즈
        max-page-size: 1000 # 최대 페이지 사이즈

logging:
  level:
    org.hibernate.SQL: debug